version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - FRONTEND_URL=http://localhost:3000
      # Add placeholders for other required environment variables
      # These would be replaced with actual values in production
      - PRIVATE_KEY=placeholder_for_testing_only
      - SHARED_SECRET=placeholder_for_testing_only
      - LENS_MAINNET_RPC_URL=https://rpc.lens.xyz
      - LENS_TESTNET_RPC_URL=https://rpc.testnet.lens.xyz
      - ENVIRONMENT=testnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
